services:
  SymSensor\ActuatorDoctrineBundle\Service\Health\Indicator\Doctrine:
    tags: ['sym_sensor_actuator.health_indicator']
    arguments:
      - [ ]


  SymSensor\ActuatorDoctrineBundle\Service\Info\Collector\Doctrine:
    tags: ['sym_sensor_actuator.info_collector']
    arguments:
      - [ ]